### ISSUE TITLE
Car Does Not Change Between Levels .. 

### ISSUE THREAD

**Issue by mabela25942** [cellul/IMTAssignment2016#3]
Car Does Not Change Between Levels ..  when the user advances to the next level .. the care remains the same..

**Comment by cellul** [comment]
This issue will be solved by changing the sprite from the level scene as shown in the image below. 
![image](https://cloud.githubusercontent.com/assets/11146977/16456560/927b0f40-3e18-11e6-9ecd-3f0a0ddca795.png)
